version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - bodyclose
    - contextcheck
    - errorlint
    - goconst
    - gocyclo
    - gosec
    - misspell
    - nakedret
    - noctx
    - revive
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
  disable:
    - depguard
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - (io.Closer).Close
        - (net/http.ResponseWriter).Write
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
      severity: high
      confidence: high
      config:
        G301: "0600"
        G302: "0600"
        G306: "0600"
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    nakedret:
      max-func-lines: 30
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
          disabled: true
        - name: unreachable-code
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - all
        - -SA1019
        - -ST1000
        - -ST1003
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - goconst
          - gosec
        path: _test\.go
      - linters:
          - gocyclo
        path: cmd/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
