run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Security
    - gosec
    - bodyclose
    - sqlclosecheck

    # Error handling
    - errcheck
    - errorlint

    # Code quality
    - govet
    - staticcheck
    - ineffassign
    - unused
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - nakedret

    # Context propagation
    - contextcheck
    - noctx

    # Style
    - revive
    - stylecheck

  disable:
    - depguard

linters-settings:
  gosec:
    severity: high
    confidence: high
    excludes:
      - G104 # Audit errors not checked - we use errcheck for this
    config:
      G301: "0600"
      G302: "0600"
      G306: "0600"

  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

  bodyclose:
    # Check that HTTP response bodies are closed

  sqlclosecheck:
    # Check that sql.Rows and sql.Stmt are closed

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  staticcheck:
    checks:
      - all
      - -SA1019 # Ignore deprecation warnings

  gocyclo:
    min-complexity: 15

  nakedret:
    max-func-lines: 30

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
        disabled: true
      - name: unreachable-code
      - name: redefines-builtin-id

  stylecheck:
    checks:
      - all
      - -ST1000 # Package comments
      - -ST1003 # Naming conventions (too strict)

issues:
  exclude-rules:
    # Exclude test files from some checks
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - goconst

    # Exclude main.go from some checks
    - path: cmd/
      linters:
        - gocyclo

  max-issues-per-linter: 50
  max-same-issues: 10
